const cyberwords = {
  words: [
    "virus",
    "proxy",
    "clave",
    "datos",
    "email",
    "fallo",
    "patch",
    "query",
    "redes",
    "token",
    "cache",
    "debug",
    "error",
    "fetch",
    "admin",
    "disco",
    "index",
    "input",
    "llave",
    "local",
    "login",
    "macro",
    "raton",
    "tecla",
    "pixel",
    "valor",
    "crack",
    "https",
    "cifra",
    "fugas",
    "nodos",
    "sniff",
    "wired",
    "cyber",
  ],
  explanations: {
    virus: "Programa malicioso que infecta sistemas. Se replica a sí mismo para propagarse a otros ordenadores.",
    proxy: "Servidor intermediario para conexiones. Puede usarse para ocultar tu IP o acceder a contenido restringido.",
    clave: "Contraseña o código de acceso. Es importante que sea segura, combinando letras, números y símbolos.",
    datos: "Información digital almacenada. Pueden ser desde un simple texto hasta complejos archivos multimedia.",
    email: "Correo electrónico. Un método de comunicación digital para enviar y recibir mensajes a través de la red.",
    fallo: "Error o mal funcionamiento del sistema. También conocido como 'bug', puede causar que un programa se cierre.",
    patch: "Actualización o parche para corregir errores. Mejora la seguridad y la funcionalidad del software.",
    query: "Consulta a base de datos, se puede llamar también petición. Se utiliza para solicitar o modificar información.",
    redes: "Sistemas de comunicación interconectados. Permiten que los dispositivos compartan recursos, como Internet.",
    token: "Código de autenticación temporal. Se usa para verificar tu identidad sin enviar tu contraseña repetidamente.",
    cache: "Memoria temporal de acceso rápido. Guarda datos usados frecuentemente para acelerar la carga de sitios web.",
    debug: "Proceso de encontrar y corregir errores. Es una parte fundamental del desarrollo de software para asegurar su calidad.",
    error: "Fallo en la ejecución del programa. Puede ser causado por código incorrecto o datos de entrada inesperados.",
    fetch: "Recuperar datos de un servidor. Es una operación común en aplicaciones web para obtener información actualizada.",
    admin: "Administrador del sistema. Usuario con los máximos privilegios para gestionar y configurar un sistema.",
    disco: "Dispositivo de almacenamiento. Puede ser un disco duro (HDD) o una unidad de estado sólido (SSD).",
    index: "Índice o lista ordenada de elementos. Facilita la búsqueda rápida de información, como en una base de datos.",
    input: "Entrada de datos al sistema. Puede provenir de un teclado, un ratón, un micrófono o un archivo.",
    llave: "Clave de cifrado o acceso. Esencial para la criptografía, permite codificar y decodificar información.",
    local: "Relativo al equipo o red local. Se opone a 'remoto', que se refiere a sistemas accesibles por internet.",
    login: "Proceso de iniciar sesión. Generalmente requiere un usuario y contraseña para verificar la identidad.",
    macro: "Secuencia automatizada de comandos. Permite ejecutar tareas repetitivas con una sola acción.",
    raton: "Dispositivo para controlar el cursor. Junto con el teclado, es el principal periférico de entrada.",
    tecla: "Dispositivo señalador. Cada una representa un carácter o una función en un teclado.",
    pixel: "Unidad mínima de imagen digital. La combinación de millones de ellos forma las imágenes en pantalla.",
    valor: "Dato o información específica. En programación, es el contenido que se asigna a una variable.",
    crack: "Romper seguridad o protección. A menudo se refiere a la modificación de software para eludir licencias.",
    https: "Protocolo web seguro encriptado. Asegura que la comunicación entre tu navegador y el sitio web es privada.",
    cifra: "Codificación de información. Proceso de transformar datos para que sean ilegibles sin la clave correcta.",
    fugas: "Filtración de datos confidenciales. Ocurre cuando información privada se expone a personas no autorizadas.",
    nodos: "Puntos de conexión en red. Puede ser un ordenador, un servidor, un router o cualquier dispositivo conectado.",
    sniff: "Interceptar tráfico de red. Técnica usada para capturar y analizar los datos que viajan por una red.",
    wired: "Conexión por cable físico. Generalmente ofrece mayor velocidad y estabilidad que las conexiones inalámbricas.",
    cyber: "Relativo al espacio digital. Abarca todo lo relacionado con la cultura de los ordenadores e internet.",
  } as Record<string, string>,
};

export default cyberwords;
