const cyberwords = {
  words: [
    "virus",
    "proxy",
    "shell",
    "clave",
    "datos",
    "email",
    "enlac",
    "fallo",
    "patch",
    "query",
    "redes",
    "token",
    "cache",
    "debug",
    "error",
    "fetch",
    "admin",
    "bloque",
    "disco",
    "index",
    "input",
    "llave",
    "local",
    "login",
    "macro",
    "mouse",
    "pixel",
    "valor",
    "zona",
    "crack",
    "https",
    "cifra",
    "fugas",
    "nodos",
    "sniff",
    "wired",
    "cyber",
    "fraud",
  ],
  explanations: {
    virus: "Programa malicioso que infecta sistemas",
    proxy: "Servidor intermediario para conexiones",
    shell: "Interfaz de línea de comandos",
    clave: "Contraseña o código de acceso",
    datos: "Información digital almacenada",
    email: "Correo electrónico",
    enlac: "Vínculo o conexión entre recursos",
    fallo: "Error o mal funcionamiento del sistema",
    patch: "Actualización para corregir errores",
    query: "Consulta a base de datos",
    redes: "Sistemas de comunicación interconectados",
    token: "Código de autenticación temporal",
    cache: "Memoria temporal de acceso rápido",
    debug: "Proceso de encontrar y corregir errores",
    error: "Fallo en la ejecución del programa",
    fetch: "Recuperar datos de un servidor",
    admin: "Administrador del sistema",
    bloque: "Unidad de datos agrupados",
    disco: "Dispositivo de almacenamiento",
    index: "Índice o lista ordenada de elementos",
    input: "Entrada de datos al sistema",
    llave: "Clave de cifrado o acceso",
    local: "Relativo al equipo o red local",
    login: "Proceso de iniciar sesión",
    macro: "Secuencia automatizada de comandos",
    mouse: "Dispositivo señalador",
    pixel: "Unidad mínima de imagen digital",
    valor: "Dato o información específica",
    zona: "Área o región de red/sistema",
    crack: "Romper seguridad o protección",
    https: "Protocolo web seguro encriptado",
    cifra: "Codificación de información",
    fugas: "Filtración de datos confidenciales",
    nodos: "Puntos de conexión en red",
    sniff: "Interceptar tráfico de red",
    wired: "Conexión por cable físico",
    cyber: "Relativo al espacio digital",
    fraud: "Fraude o engaño digital",
  } as Record<string, string>,
};

export default cyberwords;
